# quick_grid_search.py
"""
快速网格搜索：只测试最重要的参数
预计耗时：1-1.5小时
"""
# ===== 加这3行 =====
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, project_root)
os.chdir(project_root)

import os
import sys
import shutil
import json
from datetime import datetime
from itertools import product

# 测试用例（二分类）
TEST_CASES = {
    "CanAnswer": [
        "When is my rent due each month?",
        "What is the security deposit amount?",
        "Who pays for electricity and water?",
        "What's the diplomatic clause?",
        "Who is responsible for air conditioning maintenance?",
        "Can I keep pets?",
        "Who pays for repairs under $200?",
        "Can I install a dishwasher?",
        "What if the aircon breaks during the first week?",
    ],
    
    "CannotAnswer": [
        "What's the best internet service provider in Singapore?",
        "How do I apply for a work permit?",
        "Where can I buy furniture nearby?",
        "What's the weather like in Singapore?",
        "How do I open a bank account in DBS?",
        "Which primary school is good for my children?",
        "Where is the nearest MRT station?",
    ]
}

# ========== 快速参数网格（只搜索关键参数）==========
PARAM_GRID = {
    # 最重要：阈值
    'threshold': [0.70, 0.72, 0.75, 0.78, 0.80, 0.82, 0.85],
    
    # 次重要：chunk参数
    'chunk_size': [450, 500, 600],
    'chunk_overlap': [100, 150],
    
    # 固定参数（不搜索）
    'top_k_retrieval': 10,  # 固定
    'use_mmr': False,       # 固定
}

def update_config(chunk_size, chunk_overlap, threshold):
    """更新config"""
    config_content = f"""# src/config.py - AUTO GENERATED BY QUICK GRID SEARCH
import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise ValueError("Missing OPENAI_API_KEY")

EMBEDDING_MODEL = "text-embedding-3-small"
CHAT_MODEL = "gpt-4o-mini"

# Chunking parameters
CHUNK_SIZE = {chunk_size}
CHUNK_OVERLAP = {chunk_overlap}

# Retrieval parameters (FIXED)
TOP_K_RETRIEVAL = 10
TOP_K_CONTEXT = 3
USE_MMR = False
MMR_LAMBDA = 0.7

# Confidence threshold (BINARY CLASSIFICATION)
THRESHOLD_CAN_ANSWER = {threshold}
"""
    
    with open('src/config.py', 'w', encoding='utf-8') as f:
        f.write(config_content)


def rebuild_vector_store():
    """重建向量存储"""
    print("    🔨 重建向量存储...")
    if os.path.exists('vector_store'):
        shutil.rmtree('vector_store')
    os.system('python -m src.embedder > /dev/null 2>&1')


def test_configuration():
    """测试当前配置"""
    from src.chat import ask
    
    results = []
    correct = 0
    total = sum(len(questions) for questions in TEST_CASES.values())
    
    for expected, questions in TEST_CASES.items():
        for question in questions:
            try:
                response = ask(question)
                
                can_answer = response.get('can_answer', True)
                predicted = 'CanAnswer' if can_answer else 'CannotAnswer'
                
                is_correct = (predicted == expected)
                if is_correct:
                    correct += 1
                
                results.append({
                    'question': question,
                    'expected': expected,
                    'predicted': predicted,
                    'correct': is_correct,
                    'score': response.get('score', 1.0)
                })
                
            except Exception as e:
                results.append({
                    'question': question,
                    'expected': expected,
                    'predicted': 'Error',
                    'correct': False,
                    'error': str(e)
                })
    
    accuracy = (correct / total) * 100
    
    # 分类别准确率
    can_results = [r for r in results if r['expected'] == 'CanAnswer']
    cannot_results = [r for r in results if r['expected'] == 'CannotAnswer']
    
    can_acc = sum(1 for r in can_results if r['correct']) / len(can_results) * 100
    cannot_acc = sum(1 for r in cannot_results if r['correct']) / len(cannot_results) * 100
    
    return {
        'accuracy': accuracy,
        'can_answer_accuracy': can_acc,
        'cannot_answer_accuracy': cannot_acc,
        'correct': correct,
        'total': total,
        'results': results
    }


def main():
    print("="*80)
    print("⚡ 快速网格搜索")
    print("="*80)
    
    # 计算总组合数
    total_combos = (
        len(PARAM_GRID['threshold']) *
        len(PARAM_GRID['chunk_size']) *
        len(PARAM_GRID['chunk_overlap'])
    )
    
    print(f"\n📊 参数空间:")
    print(f"  Threshold: {PARAM_GRID['threshold']}")
    print(f"  Chunk size: {PARAM_GRID['chunk_size']}")
    print(f"  Chunk overlap: {PARAM_GRID['chunk_overlap']}")
    print(f"\n  (Top-K={PARAM_GRID['top_k_retrieval']}, MMR={PARAM_GRID['use_mmr']} 固定不搜索)")
    
    print(f"\n📈 总组合数: {total_combos}")
    print(f"⏱️  预计耗时: {total_combos * 1.5:.0f} 分钟 (~{total_combos * 1.5 / 60:.1f} 小时)")
    
    input("\n按Enter开始搜索 (或Ctrl+C取消)...")
    
    # 备份原始config
    if os.path.exists('src/config.py'):
        shutil.copy('src/config.py', 'src/config.py.backup')
        print("✅ 已备份原始配置")
    
    all_results = []
    current = 0
    last_chunk_params = (None, None)
    
    start_time = datetime.now()
    
    # 遍历组合（chunk参数在外层，减少重建次数）
    for chunk_size, chunk_overlap in product(PARAM_GRID['chunk_size'], PARAM_GRID['chunk_overlap']):
        
        # 判断是否需要重建向量存储
        needs_rebuild = (last_chunk_params != (chunk_size, chunk_overlap))
        
        if needs_rebuild:
            print(f"\n{'='*80}")
            print(f"📦 Chunk配置: size={chunk_size}, overlap={chunk_overlap}")
            print("="*80)
            
            # 更新config（用任意threshold，反正要重建）
            update_config(chunk_size, chunk_overlap, 0.75)
            rebuild_vector_store()
            last_chunk_params = (chunk_size, chunk_overlap)
        
        # 遍历不同阈值（不需要重建）
        for threshold in PARAM_GRID['threshold']:
            current += 1
            
            print(f"\n[{current}/{total_combos}] threshold={threshold:.2f} ", end="")
            
            # 更新config（只改阈值）
            update_config(chunk_size, chunk_overlap, threshold)
            
            # 测试
            test_result = test_configuration()
            
            result = {
                'params': {
                    'chunk_size': chunk_size,
                    'chunk_overlap': chunk_overlap,
                    'threshold': threshold
                },
                'accuracy': test_result['accuracy'],
                'can_answer_accuracy': test_result['can_answer_accuracy'],
                'cannot_answer_accuracy': test_result['cannot_answer_accuracy'],
                'correct': test_result['correct'],
                'total': test_result['total']
            }
            
            all_results.append(result)
            
            print(f"→ {test_result['accuracy']:.1f}% (Can:{test_result['can_answer_accuracy']:.0f}%, Cannot:{test_result['cannot_answer_accuracy']:.0f}%)")
    
    elapsed = (datetime.now() - start_time).total_seconds() / 60
    
    # 排序结果
    print(f"\n{'='*80}")
    print("🏆 TOP 10 最佳配置")
    print("="*80)
    
    all_results_sorted = sorted(all_results, key=lambda x: x['accuracy'], reverse=True)
    
    for i, result in enumerate(all_results_sorted[:10], 1):
        params = result['params']
        print(f"\n【第 {i} 名】准确率: {result['accuracy']:.1f}%")
        print(f"  参数:")
        print(f"    chunk_size: {params['chunk_size']}")
        print(f"    chunk_overlap: {params['chunk_overlap']}")
        print(f"    threshold: {params['threshold']}")
        print(f"  分类准确率:")
        print(f"    CanAnswer: {result['can_answer_accuracy']:.1f}%")
        print(f"    CannotAnswer: {result['cannot_answer_accuracy']:.1f}%")
    
    # 保存结果
    os.makedirs('grid_search_results', exist_ok=True)
    output_file = f'grid_search_results/quick_search_{datetime.now().strftime("%Y%m%d_%H%M%S")}.json'
    
    output = {
        'test_time': datetime.now().isoformat(),
        'elapsed_minutes': elapsed,
        'total_combinations': len(all_results),
        'param_grid': PARAM_GRID,
        'all_results': all_results_sorted
    }
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    
    print(f"\n{'='*80}")
    print(f"💾 完整结果: {output_file}")
    print(f"⏱️  实际耗时: {elapsed:.1f} 分钟")
    print("="*80)
    
    # 恢复原始config
    if os.path.exists('src/config.py.backup'):
        shutil.copy('src/config.py.backup', 'src/config.py')
        print("\n✅ 已恢复原始配置")
    
    # 生成最优配置
    best = all_results_sorted[0]
    optimal_config = f"""# OPTIMAL CONFIG (Quick Grid Search)
# Accuracy: {best['accuracy']:.1f}%
# CanAnswer: {best['can_answer_accuracy']:.1f}%
# CannotAnswer: {best['cannot_answer_accuracy']:.1f}%

CHUNK_SIZE = {best['params']['chunk_size']}
CHUNK_OVERLAP = {best['params']['chunk_overlap']}
THRESHOLD_CAN_ANSWER = {best['params']['threshold']}

# Fixed parameters
TOP_K_RETRIEVAL = 10
USE_MMR = False
"""
    
    optimal_file = 'grid_search_results/optimal_config_quick.txt'
    with open(optimal_file, 'w') as f:
        f.write(optimal_config)
    
    print(f"✅ 最优配置: {optimal_file}")
    print("\n使用方法:")
    print(f"  1. 查看 {optimal_file}")
    print(f"  2. 手动更新 src/config.py")
    print(f"  3. 重建向量存储: rm -rf vector_store && python -m src.embedder")
    print(f"  4. 测试: python test_classification.py")


if __name__ == "__main__":
    main()